name: Deploy Web Page CI/CD

on:
  push:
    branches: [ "main", "feature/actualizado" ]
  pull_request:
    branches: [ "main" ]

# Permisos necesarios para que GitHub Pages funcione correctamente
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar versión de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Ejecutar script de Python para crear el HTML
      run: python src/main.py

    - name: Configurar GitHub Pages
      uses: actions/configure-pages@v4

    - name: Subir artefacto HTML
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.' # Toma el archivo index.html generado por Python en la raíz

    - name: Desplegar en GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Mostrar enlace de la página
      run: |
        echo "===================================================="
        echo " ¡Despliegue exitoso!"
        echo " Tu página web está disponible en: ${{ steps.deployment.outputs.page_url }}"
        echo "===================================================="